name: Javascript learn

on: [push]

jobs:
  Sanyu:
    runs:-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: install dependecies
        run: npm install
      - name: Run Tests
        run: npm Tests

